//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui {
	
	
	public partial class addBet {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label gameinfo;
		
		protected System.Web.UI.WebControls.TextBox amount;
		
		protected System.Web.UI.WebControls.DropDownList teams;
		
		protected System.Web.UI.WebControls.DropDownList type;
		
		protected System.Web.UI.WebControls.Label lblStatus;
		
		protected System.Web.UI.WebControls.Button PlaceBet;
		
		protected System.Web.UI.WebControls.Button cancel;
	}
}
