//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui {
	
	
	public partial class addMatch {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList ploeg1;
		
		protected System.Web.UI.WebControls.TextBox score1;
		
		protected System.Web.UI.WebControls.DropDownList ploeg2;
		
		protected System.Web.UI.WebControls.TextBox score2;
		
		protected System.Web.UI.WebControls.DropDownList dag;
		
		protected System.Web.UI.WebControls.DropDownList maand;
		
		protected System.Web.UI.WebControls.DropDownList jaar;
		
		protected System.Web.UI.WebControls.Label statusLabel;
		
		protected System.Web.UI.WebControls.Button matchadd;
		
		protected System.Web.UI.WebControls.Button returnHome;
	}
}
