//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui {
	
	
	public partial class addUser {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.TextBox txtLastName;
		
		protected System.Web.UI.WebControls.TextBox txtAddr;
		
		protected System.Web.UI.WebControls.TextBox txtGsm;
		
		protected System.Web.UI.WebControls.TextBox txtBalance;
		
		protected System.Web.UI.WebControls.Label alertlabel;
		
		protected System.Web.UI.WebControls.Button addusr;
		
		protected System.Web.UI.WebControls.Button @return;
	}
}
