//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui {
	
	
	public partial class Admin {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button addUser;
		
		protected System.Web.UI.WebControls.Button addMatch;
		
		protected System.Web.UI.WebControls.Button addPloeg;
		
		protected System.Web.UI.WebControls.ListBox listGames;
		
		protected System.Web.UI.WebControls.Button updateGame;
	}
}
