//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui {
	
	
	public partial class mainForm {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label labelNaam;
		
		protected System.Web.UI.WebControls.Label labelAdress;
		
		protected System.Web.UI.WebControls.Label labelGsm;
		
		protected System.Web.UI.WebControls.Label labelBalance;
		
		protected System.Web.UI.WebControls.Button btnAddBalance;
		
		protected System.Web.UI.WebControls.Label labelTitleGamebox;
		
		protected System.Web.UI.WebControls.ListBox listGames;
		
		protected System.Web.UI.WebControls.Button btnPlaceBet;
		
		protected System.Web.UI.WebControls.ListBox listBets;
	}
}
