//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui {
	
	
	public partial class updateGame {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label thuis;
		
		protected System.Web.UI.WebControls.TextBox scoreThuis;
		
		protected System.Web.UI.WebControls.Label uit;
		
		protected System.Web.UI.WebControls.TextBox scoreUit;
		
		protected System.Web.UI.WebControls.Button finish;
		
		protected System.Web.UI.WebControls.Button cancel;
	}
}
